# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HQu5kz02HfH8ufjG-BElNKXNHO7TU4zC
"""

from turtle import *
from time import sleep
bgcolor("black")
#Creates two Turtle objects and stores them in a list t.
t=[Turtle(),Turtle()]

#Sets the pen width, color, shape, and speed of the turtles using various methods like width(), color(), shape(), speed(), etc.
x = 6
#Lifts up the pen (pu()) and moves each turtle to a starting position (fd() and seth() methods).
colors=["red","aqua","blue"]
for index, i in enumerate(t):
  i.speed(0)
  i.color("white")
  i.shape("circle")
  i.shapesize(0.3)
  i.width(3)
  i.pu()
  i.seth(90)
  i.fd(350)
  i.seth(-180)
  i.pd()
t[0].pu()

#Sets the delay to 0 using the delay() method and the speed to 0 using the speed() method.
delay(0)
speed(0)
#Hides the turtle using the ht() method and sleeps for 4 seconds using the sleep() method.
ht()
sleep(4)
#Loops over the colors list and sets the pen color using the color() method.
#Loops over 360 degrees and moves the first turtle forward by x pixels and turns left by 1 degree using the fd() and lt() methods.
#Lifts up the pen (pu()), moves to the first turtle's position (goto() method), puts the pen down (pd()), moves the second turtle forward by 2*x pixels and turns left by 2 degrees using the fd() and lt() methods.
#Moves to the second turtle's position (goto() method) and repeats the loop until all degrees are covered.
for i in colors:
  color(i)
  for i in range(360):
    t[0].fd(x)
    t[0].lt(1)
    pu()
    goto(t[0].pos())
    pd()
    t[1].fd(2 * x)
    t[1].lt(2)
    goto(t[1].pos())

#Ends the turtle graphics using the done() method.    
done()