# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oi6NYbGSIUeaBY0JkBt53d-KldiGc6CT
"""

from barcode import EAN13
from barcode.writer import ImageWriter

def generate_barcode(code, filename):
    # Create an EAN13 barcode object
    barcode = EAN13(code, writer=ImageWriter())

    # Save the barcode image to a file
    barcode.save(filename)

# Generate a barcode with code "123456789012"
generate_barcode('0715656710', 'barcode1.png')